# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heyum_DBD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Heyum_DBD

pod 'FSCalendar'

end
